export const SET_BED_TYPES = "SET_BED_TYPES";
export type SET_BED_TYPES = typeof SET_BED_TYPES;

export const ONBOARDING_STEP_COMPLETED = "ONBOARDING_STEP_COMPLETED";
export type ONBOARDING_STEP_COMPLETED = typeof ONBOARDING_STEP_COMPLETED;

export const LOCATION_SET = "LOCATION_SET";
export type LOCATION_SET = typeof LOCATION_SET;

export const LOAD_TASKS = "LOAD_TASKS";
export type LOAD_TASKS = typeof LOAD_TASKS;
